baseURL = "/"
languageCode = "en-us"
theme = "learn"
title = "Scalable Networking on AWS"
[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
showVisitedLinks = true
disableBreadcrumb = false
disableNextPrev = false
themeVariant = "blue"